[project]
name = "envless-comfyui-geometrypack"
description = "CGAL - Blender - IGL - Paraview - VTK. Geometry processing nodes for ComfyUI - mesh manipulation, remeshing, hole filling, UV unwrapping, Alpha Wrapping, and 3D visualization"
version = "0.2.2"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/not-pozzetti/ENVLESSComfyUI-GeometryPack"

[tool.comfy]
PublisherId = "not-pozzetti"
DisplayName = "GeometryPack"
Icon = ""
