# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ENVLESSComfyUI-GeometryPack Contributors

"""
Blender I/O nodes - requires bpy
"""

from .load_mesh_blend import NODE_CLASS_MAPPINGS as LOAD_MESH_BLEND_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_MESH_BLEND_DISP
from .load_mesh_fbx import NODE_CLASS_MAPPINGS as LOAD_MESH_FBX_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_MESH_FBX_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(LOAD_MESH_BLEND_MAPS)
NODE_CLASS_MAPPINGS.update(LOAD_MESH_FBX_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_MESH_BLEND_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_MESH_FBX_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
